[package]
name = "labels"
version = "0.4.0"
authors = ["ink8bit <ink8bit@users.noreply.github.com>"]
edition = "2021"

publish = false
description = "CLI utility to update labels in GitHub repo"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.2", features = ["cargo"] }
serde_json = "1.0.86"
serde = { version = "1.0.147", features = ["derive"] }
reqwest = { version = "0.11.12", features = ["json"] }
tokio = { version = "1.16.1", features = ["full"] }
terminal-spinners = "0.3.2"
